// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/44be13ae844ec0721109542d5902e41438d72855/extend/extend.d.ts
declare module "extend" {

    function extend(deepOrObject:boolean | Object, ...objectN: Object[]): any;
    namespace extend {}
    export = extend;
}
